name: Terraform

on:
  push:
    branches:
      - sanket
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Replace with the desired Terraform version

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1 # Set to your desired region
          echo "check aws cli identity"
          aws sts get-caller-identity



      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      


      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Terraform Plan Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

      - name: Check Terraform Plan
        if: failure()
        run: |
          echo "Terraform plan failed. Check the logs for more details."
          exit 1

      - name: Create Pull Request
        if: success() && github.event_name == 'push'
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          target_branch: main
          pr_title: "Automated PR: Terraform Plan Successful"
          pr_body: |
            This pull request was automatically created because the Terraform plan was successful.
 






    

