name: Terraform Workflow

on:
  push:
    branches:
      - main
      - sanket
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          echo "check aws cli identity"
          aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete Existing Plan File
        run: |
          if [ -f plan.out ]; then
            echo "Deleting existing plan.out"
            rm plan.out
          else
            echo "No existing plan.out file found"
          fi

      - name: Terraform Plan
        run: terraform plan -out=plan.out
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check Terraform Plan
        if: failure()
        run: |
          echo "Terraform plan failed. Check the logs for more details."
          exit 1

      - name: Upload Terraform Plan Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

      - name: Create Pull Request
   
